---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.

Throughout this course, a main area of improvement for me was writing more efficient and readable code. As the weeks went on, I had less growing areas and more success areas. As a computer science student, the coding aspect of this class wasn't intimidating to me, but to my surprise I still had a lot to learn! I understand what it means to write tidy/ efficient code and can easily identify code that doesn't uphold quality. But like I mentioned, since I have written a lot of code the past few years, it felt pretty natural for me to understand what tidy/ efficient code is and how to achieve it. This involved making sure the code looked pleasing and was easy to read, but also not repeating functions, creating unnecessary objects, etc. For example, I used the map2() function in challenge 2 to streamline the process of adding annotations to my graph, reducing repetition and making the code easier to maintain. This was an area where I would say I had quick improvement and it didn't feel too difficult for me.

Another area I think I had improvement in and had a harder time with initially was my data visualization techniques. In every computer science class I have taken so far, visuals aren't really a concern. The goal is to complete the projects efficiently and come up with a performance enhancing solution. But now, in this class, there was a big emphasis on not just creating visuals, but making sure they are insightful and creative. So, although a visual may be accurate and display all the necessary information, this doesn't mean it's great! It is really helpful to improve visualizations by changing the fonts, colors, titles, or even thinking about what type of visualization to make! In the beginning of the class, I would just make a plot or a table and consider it good. Now I am more thoughtful about what information I am displaying and how. In the first few weeks, I didn't think much about my visualizations, as long as they displayed the correct information. However, by week 7, 8, and 9, you can see I put thought in visualizations (changing the colors, the titles, the type of visualizations, making my tables prettier, etc.). Specifically in dvs-7-1, I created a pretty and creative table (changed the title/ column names, added color/ a footnote, made the values be percents). In dvs-3-3, I created an informative ggplot with a creative title, fun colors, and removed the legened to not have redundant information!

I think this course has taught me not only to write efficient/ tidy code to get the information I need, but also to effectively display/ share that information.







